#%RAML 1.0 NamedExample

[
    {
        "loan_id": "LN0001",
        "borrower_name": "Borrower 1",
        "loan_amount": 37737.56,
        "loan_status": "Pending",
        "loan_date": "2023-08-01"
    },
    {
        "loan_id": "LN0002",
        "borrower_name": "Borrower 2",
        "loan_amount": 32681.41,
        "loan_status": "Disbursed",
        "loan_date": "2022-11-27"
    },
    {
        "loan_id": "LN0003",
        "borrower_name": "Borrower 3",
        "loan_amount": 29422.53,
        "loan_status": "Pending",
        "loan_date": "2023-08-08"
    },
    {
        "loan_id": "LN0004",
        "borrower_name": "Borrower 4",
        "loan_amount": 1402.79,
        "loan_status": "Rejected",
        "loan_date": "2024-08-06"
    },
    {
        "loan_id": "LN0005",
        "borrower_name": "Borrower 5",
        "loan_amount": 9082.72,
        "loan_status": "Closed",
        "loan_date": "2023-12-09"
    },
    {
        "loan_id": "LN0006",
        "borrower_name": "Borrower 6",
        "loan_amount": 35762.52,
        "loan_status": "Pending",
        "loan_date": "2023-09-13"
    },
    {
        "loan_id": "LN0007",
        "borrower_name": "Borrower 7",
        "loan_amount": 3127.17,
        "loan_status": "Rejected",
        "loan_date": "2022-11-26"
    },
    {
        "loan_id": "LN0008",
        "borrower_name": "Borrower 8",
        "loan_amount": 5590.82,
        "loan_status": "Disbursed",
        "loan_date": "2023-01-16"
    },
    {
        "loan_id": "LN0009",
        "borrower_name": "Borrower 9",
        "loan_amount": 29287.16,
        "loan_status": "Closed",
        "loan_date": "2023-01-10"
    },
    {
        "loan_id": "LN0010",
        "borrower_name": "Borrower 10",
        "loan_amount": 27367.9,
        "loan_status": "Pending",
        "loan_date": "2022-11-26"
    },
    {
        "loan_id": "LN0011",
        "borrower_name": "Borrower 11",
        "loan_amount": 3692.42,
        "loan_status": "Closed",
        "loan_date": "2023-06-05"
    },
    {
        "loan_id": "LN0012",
        "borrower_name": "Borrower 12",
        "loan_amount": 4889.15,
        "loan_status": "Approved",
        "loan_date": "2023-12-29"
    }
]