#%RAML 1.0 ResourceType
put:
  description: <<addDescription>>
  queryParameters: <<queryParams>>
  body:
    application/json:
      type: <<bodyType>>
  responses: 
    201:
      body: 
        application/json:
          example: <<getResponseExample>>
          type: <<getResponseType>>